
/*******************************************************************************
   Chinook Database - Version 1.4
   Script: Chinook_MySql_AutoIncrementPKs.sql
   Description: Creates and populates the Chinook database.
   DB Server: MySql
   Author: Luis Rocha
   License: http://www.codeplex.com/ChinookDatabase/license
********************************************************************************/

/*******************************************************************************
   Drop database if it exists
********************************************************************************/
/*DROP DATABASE IF EXISTS `Chinook`;*/


/*******************************************************************************
   Create database
********************************************************************************/
CREATE DATABASE IF NOT EXISTS `audio`;


USE `audio`;


/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE IF NOT EXISTS `Album`
(
    `AlbumId` INT NOT NULL AUTO_INCREMENT,
    `Title` NVARCHAR(160) NOT NULL,
    `ArtistId` INT NOT NULL,
    CONSTRAINT `PK_Album` PRIMARY KEY  (`AlbumId`)
);

CREATE TABLE IF NOT EXISTS `Artist`
(
    `ArtistId` INT NOT NULL AUTO_INCREMENT,
    `Name` NVARCHAR(120),
    CONSTRAINT `PK_Artist` PRIMARY KEY  (`ArtistId`)
);


/*******************************************************************************
   Create Primary Key Unique Indexes
********************************************************************************/

/*******************************************************************************
   Create Foreign Keys
********************************************************************************/
ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId`
    FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX `IFK_AlbumArtistId` ON `Album` (`ArtistId`);

/*******************************************************************************
   Populate Tables
********************************************************************************/

INSERT INTO `Artist` (`Name`) VALUES ('AC/DC');
INSERT INTO `Artist` (`Name`) VALUES ('Accept');
INSERT INTO `Artist` (`Name`) VALUES ('Aerosmith');
INSERT INTO `Artist` (`Name`) VALUES ('Alanis Morissette');
INSERT INTO `Artist` (`Name`) VALUES ('Alice In Chains');
INSERT INTO `Artist` (`Name`) VALUES ('Antônio Carlos Jobim');
INSERT INTO `Artist` (`Name`) VALUES ('Apocalyptica');
INSERT INTO `Artist` (`Name`) VALUES ('Audioslave');
INSERT INTO `Artist` (`Name`) VALUES ('BackBeat');
INSERT INTO `Artist` (`Name`) VALUES ('Billy Cobham');
INSERT INTO `Artist` (`Name`) VALUES ('Black Label Society');
INSERT INTO `Artist` (`Name`) VALUES ('Black Sabbath');
INSERT INTO `Artist` (`Name`) VALUES ('Body Count');
INSERT INTO `Artist` (`Name`) VALUES ('Bruce Dickinson');
INSERT INTO `Artist` (`Name`) VALUES ('Buddy Guy');
INSERT INTO `Artist` (`Name`) VALUES ('Caetano Veloso');
INSERT INTO `Artist` (`Name`) VALUES ('Chico Buarque');
INSERT INTO `Artist` (`Name`) VALUES ('Chico Science & Nação Zumbi');
INSERT INTO `Artist` (`Name`) VALUES ('Cidade Negra');
INSERT INTO `Artist` (`Name`) VALUES ('Cláudio Zoli');
INSERT INTO `Artist` (`Name`) VALUES ('Various Artists');
INSERT INTO `Artist` (`Name`) VALUES ('Led Zeppelin');
INSERT INTO `Artist` (`Name`) VALUES ('Frank Zappa & Captain Beefheart');
INSERT INTO `Artist` (`Name`) VALUES ('Marcos Valle');
INSERT INTO `Artist` (`Name`) VALUES ('Milton Nascimento & Bebeto');
INSERT INTO `Artist` (`Name`) VALUES ('Azymuth');
INSERT INTO `Artist` (`Name`) VALUES ('Gilberto Gil');
INSERT INTO `Artist` (`Name`) VALUES ('João Gilberto');
INSERT INTO `Artist` (`Name`) VALUES ('Bebel Gilberto');
INSERT INTO `Artist` (`Name`) VALUES ('Jorge Vercilo');
INSERT INTO `Artist` (`Name`) VALUES ('Baby Consuelo');
INSERT INTO `Artist` (`Name`) VALUES ('Ney Matogrosso');
INSERT INTO `Artist` (`Name`) VALUES ('Luiz Melodia');
INSERT INTO `Artist` (`Name`) VALUES ('Nando Reis');
INSERT INTO `Artist` (`Name`) VALUES ('Pedro Luís & A Parede');
INSERT INTO `Artist` (`Name`) VALUES ('O Rappa');
INSERT INTO `Artist` (`Name`) VALUES ('Ed Motta');
INSERT INTO `Artist` (`Name`) VALUES ('Banda Black Rio');
INSERT INTO `Artist` (`Name`) VALUES ('Fernanda Porto');
INSERT INTO `Artist` (`Name`) VALUES ('Os Cariocas');
INSERT INTO `Artist` (`Name`) VALUES ('Elis Regina');
INSERT INTO `Artist` (`Name`) VALUES ('Milton Nascimento');
INSERT INTO `Artist` (`Name`) VALUES ('A Cor Do Som');
INSERT INTO `Artist` (`Name`) VALUES ('Kid Abelha');
INSERT INTO `Artist` (`Name`) VALUES ('Sandra De Sá');
INSERT INTO `Artist` (`Name`) VALUES ('Jorge Ben');
INSERT INTO `Artist` (`Name`) VALUES ('Hermeto Pascoal');
INSERT INTO `Artist` (`Name`) VALUES ('Barão Vermelho');
INSERT INTO `Artist` (`Name`) VALUES ('Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO `Artist` (`Name`) VALUES ('Metallica');
INSERT INTO `Artist` (`Name`) VALUES ('Queen');
INSERT INTO `Artist` (`Name`) VALUES ('Kiss');
INSERT INTO `Artist` (`Name`) VALUES ('Spyro Gyra');
INSERT INTO `Artist` (`Name`) VALUES ('Green Day');
INSERT INTO `Artist` (`Name`) VALUES ('David Coverdale');
INSERT INTO `Artist` (`Name`) VALUES ('Gonzaguinha');
INSERT INTO `Artist` (`Name`) VALUES ('Os Mutantes');
INSERT INTO `Artist` (`Name`) VALUES ('Deep Purple');
INSERT INTO `Artist` (`Name`) VALUES ('Santana');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Dave Matthews');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Everlast');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Rob Thomas');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. The Project G&B');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Maná');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Eagle-Eye Cherry');
INSERT INTO `Artist` (`Name`) VALUES ('Santana Feat. Eric Clapton');
INSERT INTO `Artist` (`Name`) VALUES ('Miles Davis');
INSERT INTO `Artist` (`Name`) VALUES ('Gene Krupa');
INSERT INTO `Artist` (`Name`) VALUES ('Toquinho & Vinícius');
INSERT INTO `Artist` (`Name`) VALUES ('Vinícius De Moraes & Baden Powell');
INSERT INTO `Artist` (`Name`) VALUES ('Vinícius De Moraes');
INSERT INTO `Artist` (`Name`) VALUES ('Vinícius E Qurteto Em Cy');
INSERT INTO `Artist` (`Name`) VALUES ('Vinícius E Odette Lara');
INSERT INTO `Artist` (`Name`) VALUES ('Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO `Artist` (`Name`) VALUES ('Creedence Clearwater Revival');
INSERT INTO `Artist` (`Name`) VALUES ('Cássia Eller');
INSERT INTO `Artist` (`Name`) VALUES ('Def Leppard');
INSERT INTO `Artist` (`Name`) VALUES ('Dennis Chambers');
INSERT INTO `Artist` (`Name`) VALUES ('Djavan');
INSERT INTO `Artist` (`Name`) VALUES ('Eric Clapton');
INSERT INTO `Artist` (`Name`) VALUES ('Faith No More');
INSERT INTO `Artist` (`Name`) VALUES ('Falamansa');
INSERT INTO `Artist` (`Name`) VALUES ('Foo Fighters');
INSERT INTO `Artist` (`Name`) VALUES ('Frank Sinatra');
INSERT INTO `Artist` (`Name`) VALUES ('Funk Como Le Gusta');
INSERT INTO `Artist` (`Name`) VALUES ('Godsmack');
INSERT INTO `Artist` (`Name`) VALUES ('Guns N'' Roses');
INSERT INTO `Artist` (`Name`) VALUES ('Incognito');
INSERT INTO `Artist` (`Name`) VALUES ('Iron Maiden');
INSERT INTO `Artist` (`Name`) VALUES ('James Brown');
INSERT INTO `Artist` (`Name`) VALUES ('Jamiroquai');
INSERT INTO `Artist` (`Name`) VALUES ('JET');
INSERT INTO `Artist` (`Name`) VALUES ('Jimi Hendrix');
INSERT INTO `Artist` (`Name`) VALUES ('Joe Satriani');
INSERT INTO `Artist` (`Name`) VALUES ('Jota Quest');
INSERT INTO `Artist` (`Name`) VALUES ('João Suplicy');
INSERT INTO `Artist` (`Name`) VALUES ('Judas Priest');
INSERT INTO `Artist` (`Name`) VALUES ('Legião Urbana');
INSERT INTO `Artist` (`Name`) VALUES ('Lenny Kravitz');
INSERT INTO `Artist` (`Name`) VALUES ('Lulu Santos');
INSERT INTO `Artist` (`Name`) VALUES ('Marillion');
INSERT INTO `Artist` (`Name`) VALUES ('Marisa Monte');
INSERT INTO `Artist` (`Name`) VALUES ('Marvin Gaye');
INSERT INTO `Artist` (`Name`) VALUES ('Men At Work');
INSERT INTO `Artist` (`Name`) VALUES ('Motörhead');
INSERT INTO `Artist` (`Name`) VALUES ('Motörhead & Girlschool');
INSERT INTO `Artist` (`Name`) VALUES ('Mônica Marianno');
INSERT INTO `Artist` (`Name`) VALUES ('Mötley Crüe');
INSERT INTO `Artist` (`Name`) VALUES ('Nirvana');
INSERT INTO `Artist` (`Name`) VALUES ('O Terço');
INSERT INTO `Artist` (`Name`) VALUES ('Olodum');
INSERT INTO `Artist` (`Name`) VALUES ('Os Paralamas Do Sucesso');
INSERT INTO `Artist` (`Name`) VALUES ('Ozzy Osbourne');
INSERT INTO `Artist` (`Name`) VALUES ('Page & Plant');
INSERT INTO `Artist` (`Name`) VALUES ('Passengers');
INSERT INTO `Artist` (`Name`) VALUES ('Paul D''Ianno');
INSERT INTO `Artist` (`Name`) VALUES ('Pearl Jam');
INSERT INTO `Artist` (`Name`) VALUES ('Peter Tosh');
INSERT INTO `Artist` (`Name`) VALUES ('Pink Floyd');
INSERT INTO `Artist` (`Name`) VALUES ('Planet Hemp');
INSERT INTO `Artist` (`Name`) VALUES ('R.E.M. Feat. Kate Pearson');
INSERT INTO `Artist` (`Name`) VALUES ('R.E.M. Feat. KRS-One');
INSERT INTO `Artist` (`Name`) VALUES ('R.E.M.');
INSERT INTO `Artist` (`Name`) VALUES ('Raimundos');
INSERT INTO `Artist` (`Name`) VALUES ('Raul Seixas');
INSERT INTO `Artist` (`Name`) VALUES ('Red Hot Chili Peppers');
INSERT INTO `Artist` (`Name`) VALUES ('Rush');
INSERT INTO `Artist` (`Name`) VALUES ('Simply Red');
INSERT INTO `Artist` (`Name`) VALUES ('Skank');
INSERT INTO `Artist` (`Name`) VALUES ('Smashing Pumpkins');
INSERT INTO `Artist` (`Name`) VALUES ('Soundgarden');
INSERT INTO `Artist` (`Name`) VALUES ('Stevie Ray Vaughan & Double Trouble');
INSERT INTO `Artist` (`Name`) VALUES ('Stone Temple Pilots');
INSERT INTO `Artist` (`Name`) VALUES ('System Of A Down');
INSERT INTO `Artist` (`Name`) VALUES ('Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO `Artist` (`Name`) VALUES ('The Black Crowes');
INSERT INTO `Artist` (`Name`) VALUES ('The Clash');
INSERT INTO `Artist` (`Name`) VALUES ('The Cult');
INSERT INTO `Artist` (`Name`) VALUES ('The Doors');
INSERT INTO `Artist` (`Name`) VALUES ('The Police');
INSERT INTO `Artist` (`Name`) VALUES ('The Rolling Stones');
INSERT INTO `Artist` (`Name`) VALUES ('The Tea Party');
INSERT INTO `Artist` (`Name`) VALUES ('The Who');
INSERT INTO `Artist` (`Name`) VALUES ('Tim Maia');
INSERT INTO `Artist` (`Name`) VALUES ('Titãs');
INSERT INTO `Artist` (`Name`) VALUES ('Battlestar Galactica');
INSERT INTO `Artist` (`Name`) VALUES ('Heroes');
INSERT INTO `Artist` (`Name`) VALUES ('Lost');
INSERT INTO `Artist` (`Name`) VALUES ('U2');
INSERT INTO `Artist` (`Name`) VALUES ('UB40');
INSERT INTO `Artist` (`Name`) VALUES ('Van Halen');
INSERT INTO `Artist` (`Name`) VALUES ('Velvet Revolver');
INSERT INTO `Artist` (`Name`) VALUES ('Whitesnake');
INSERT INTO `Artist` (`Name`) VALUES ('Zeca Pagodinho');
INSERT INTO `Artist` (`Name`) VALUES ('The Office');
INSERT INTO `Artist` (`Name`) VALUES ('Dread Zeppelin');
INSERT INTO `Artist` (`Name`) VALUES ('Battlestar Galactica (Classic)');
INSERT INTO `Artist` (`Name`) VALUES ('Aquaman');
INSERT INTO `Artist` (`Name`) VALUES ('Christina Aguilera featuring BigElf');
INSERT INTO `Artist` (`Name`) VALUES ('Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO `Artist` (`Name`) VALUES ('Los Lonely Boys');
INSERT INTO `Artist` (`Name`) VALUES ('Corinne Bailey Rae');
INSERT INTO `Artist` (`Name`) VALUES ('Dhani Harrison & Jakob Dylan');
INSERT INTO `Artist` (`Name`) VALUES ('Jackson Browne');
INSERT INTO `Artist` (`Name`) VALUES ('Avril Lavigne');
INSERT INTO `Artist` (`Name`) VALUES ('Big & Rich');
INSERT INTO `Artist` (`Name`) VALUES ('Youssou N''Dour');
INSERT INTO `Artist` (`Name`) VALUES ('Black Eyed Peas');
INSERT INTO `Artist` (`Name`) VALUES ('Jack Johnson');
INSERT INTO `Artist` (`Name`) VALUES ('Ben Harper');
INSERT INTO `Artist` (`Name`) VALUES ('Snow Patrol');
INSERT INTO `Artist` (`Name`) VALUES ('Matisyahu');
INSERT INTO `Artist` (`Name`) VALUES ('The Postal Service');
INSERT INTO `Artist` (`Name`) VALUES ('Jaguares');
INSERT INTO `Artist` (`Name`) VALUES ('The Flaming Lips');
INSERT INTO `Artist` (`Name`) VALUES ('Jack''s Mannequin & Mick Fleetwood');
INSERT INTO `Artist` (`Name`) VALUES ('Regina Spektor');
INSERT INTO `Artist` (`Name`) VALUES ('Scorpions');
INSERT INTO `Artist` (`Name`) VALUES ('House Of Pain');
INSERT INTO `Artist` (`Name`) VALUES ('Xis');
INSERT INTO `Artist` (`Name`) VALUES ('Nega Gizza');
INSERT INTO `Artist` (`Name`) VALUES ('Gustavo & Andres Veiga & Salazar');
INSERT INTO `Artist` (`Name`) VALUES ('Rodox');
INSERT INTO `Artist` (`Name`) VALUES ('Charlie Brown Jr.');
INSERT INTO `Artist` (`Name`) VALUES ('Pedro Luís E A Parede');
INSERT INTO `Artist` (`Name`) VALUES ('Los Hermanos');
INSERT INTO `Artist` (`Name`) VALUES ('Mundo Livre S/A');
INSERT INTO `Artist` (`Name`) VALUES ('Otto');
INSERT INTO `Artist` (`Name`) VALUES ('Instituto');
INSERT INTO `Artist` (`Name`) VALUES ('Nação Zumbi');
INSERT INTO `Artist` (`Name`) VALUES ('DJ Dolores & Orchestra Santa Massa');
INSERT INTO `Artist` (`Name`) VALUES ('Seu Jorge');
INSERT INTO `Artist` (`Name`) VALUES ('Sabotage E Instituto');
INSERT INTO `Artist` (`Name`) VALUES ('Stereo Maracana');
INSERT INTO `Artist` (`Name`) VALUES ('Cake');
INSERT INTO `Artist` (`Name`) VALUES ('Aisha Duo');
INSERT INTO `Artist` (`Name`) VALUES ('Habib Koité and Bamada');
INSERT INTO `Artist` (`Name`) VALUES ('Karsh Kale');
INSERT INTO `Artist` (`Name`) VALUES ('The Posies');
INSERT INTO `Artist` (`Name`) VALUES ('Luciana Souza/Romero Lubambo');
INSERT INTO `Artist` (`Name`) VALUES ('Aaron Goldberg');
INSERT INTO `Artist` (`Name`) VALUES ('Nicolaus Esterhazy Sinfonia');
INSERT INTO `Artist` (`Name`) VALUES ('Temple of the Dog');
INSERT INTO `Artist` (`Name`) VALUES ('Chris Cornell');
INSERT INTO `Artist` (`Name`) VALUES ('Alberto Turco & Nova Schola Gregoriana');
INSERT INTO `Artist` (`Name`) VALUES ('Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO `Artist` (`Name`) VALUES ('English Concert & Trevor Pinnock');
INSERT INTO `Artist` (`Name`) VALUES ('Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO `Artist` (`Name`) VALUES ('Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO `Artist` (`Name`) VALUES ('Wilhelm Kempff');
INSERT INTO `Artist` (`Name`) VALUES ('Yo-Yo Ma');
INSERT INTO `Artist` (`Name`) VALUES ('Scholars Baroque Ensemble');
INSERT INTO `Artist` (`Name`) VALUES ('Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO `Artist` (`Name`) VALUES ('Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO `Artist` (`Name`) VALUES ('Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO `Artist` (`Name`) VALUES ('Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO `Artist` (`Name`) VALUES ('Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO `Artist` (`Name`) VALUES ('Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO `Artist` (`Name`) VALUES ('Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO `Artist` (`Name`) VALUES ('Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO `Artist` (`Name`) VALUES ('Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO `Artist` (`Name`) VALUES ('London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO `Artist` (`Name`) VALUES ('Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO `Artist` (`Name`) VALUES ('Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO `Artist` (`Name`) VALUES ('Eugene Ormandy');
INSERT INTO `Artist` (`Name`) VALUES ('Luciano Pavarotti');
INSERT INTO `Artist` (`Name`) VALUES ('Leonard Bernstein & New York Philharmonic');
INSERT INTO `Artist` (`Name`) VALUES ('Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO `Artist` (`Name`) VALUES ('Aaron Copland & London Symphony Orchestra');
INSERT INTO `Artist` (`Name`) VALUES ('Ton Koopman');
INSERT INTO `Artist` (`Name`) VALUES ('Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO `Artist` (`Name`) VALUES ('Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO `Artist` (`Name`) VALUES ('Orchestra of The Age of Enlightenment');
INSERT INTO `Artist` (`Name`) VALUES ('Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO `Artist` (`Name`) VALUES ('James Levine');
INSERT INTO `Artist` (`Name`) VALUES ('Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO `Artist` (`Name`) VALUES ('Maurizio Pollini');
INSERT INTO `Artist` (`Name`) VALUES ('Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO `Artist` (`Name`) VALUES ('Gustav Mahler');
INSERT INTO `Artist` (`Name`) VALUES ('Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO `Artist` (`Name`) VALUES ('Edo de Waart & San Francisco Symphony');
INSERT INTO `Artist` (`Name`) VALUES ('Antal Doráti & London Symphony Orchestra');
INSERT INTO `Artist` (`Name`) VALUES ('Choir Of Westminster Abbey & Simon Preston');
INSERT INTO `Artist` (`Name`) VALUES ('Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO `Artist` (`Name`) VALUES ('Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO `Artist` (`Name`) VALUES ('The King''s Singers');
INSERT INTO `Artist` (`Name`) VALUES ('Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO `Artist` (`Name`) VALUES ('Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO `Artist` (`Name`) VALUES ('Christopher O''Riley');
INSERT INTO `Artist` (`Name`) VALUES ('Fretwork');
INSERT INTO `Artist` (`Name`) VALUES ('Amy Winehouse');
INSERT INTO `Artist` (`Name`) VALUES ('Calexico');
INSERT INTO `Artist` (`Name`) VALUES ('Otto Klemperer & Philharmonia Orchestra');
INSERT INTO `Artist` (`Name`) VALUES ('Yehudi Menuhin');
INSERT INTO `Artist` (`Name`) VALUES ('Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO `Artist` (`Name`) VALUES ('Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO `Artist` (`Name`) VALUES ('Les Arts Florissants & William Christie');
INSERT INTO `Artist` (`Name`) VALUES ('The 12 Cellists of The Berlin Philharmonic');
INSERT INTO `Artist` (`Name`) VALUES ('Adrian Leaper & Doreen de Feis');
INSERT INTO `Artist` (`Name`) VALUES ('Roger Norrington, London Classical Players');
INSERT INTO `Artist` (`Name`) VALUES ('Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO `Artist` (`Name`) VALUES ('Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO `Artist` (`Name`) VALUES ('Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO `Artist` (`Name`) VALUES ('Julian Bream');
INSERT INTO `Artist` (`Name`) VALUES ('Martin Roscoe');
INSERT INTO `Artist` (`Name`) VALUES ('Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO `Artist` (`Name`) VALUES ('Itzhak Perlman');
INSERT INTO `Artist` (`Name`) VALUES ('Michele Campanella');
INSERT INTO `Artist` (`Name`) VALUES ('Gerald Moore');
INSERT INTO `Artist` (`Name`) VALUES ('Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO `Artist` (`Name`) VALUES ('Emerson String Quartet');
INSERT INTO `Artist` (`Name`) VALUES ('C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO `Artist` (`Name`) VALUES ('Nash Ensemble');
INSERT INTO `Artist` (`Name`) VALUES ('Philip Glass Ensemble');

INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('For Those About To Rock We Salute You', 1);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Balls to the Wall', 2);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Restless and Wild', 2);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Let There Be Rock', 1);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Big Ones', 3);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Jagged Little Pill', 4);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Facelift', 5);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Warner 25 Anos', 6);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Plays Metallica By Four Cellos', 7);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Audioslave', 8);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Out Of Exile', 8);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('BackBeat Soundtrack', 9);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of Billy Cobham', 10);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Alcohol Fueled Brewtality Live! [Disc 1]', 11);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Alcohol Fueled Brewtality Live! [Disc 2]', 11);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Black Sabbath', 12);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Black Sabbath Vol. 4 (Remaster)', 12);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Body Count', 13);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chemical Wedding', 14);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of Buddy Guy - The Millenium Collection', 15);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Prenda Minha', 16);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Sozinho Remix Ao Vivo', 16);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Minha Historia', 17);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Afrociberdelia', 18);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Da Lama Ao Caos', 18);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Acústico MTV [Live]', 19);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cidade Negra - Hits', 19);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Na Pista', 20);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Axé Bahia 2001', 21);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('BBC Sessions [Disc 1] [Live]', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bongo Fury', 23);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Carnaval 2001', 21);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chill: Brazil (Disc 1)', 24);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chill: Brazil (Disc 2)', 6);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Garage Inc. (Disc 1)', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Greatest Hits II', 51);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Greatest Kiss', 52);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Heart of the Night', 53);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('International Superhits', 54);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Into The Light', 55);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Meus Momentos', 56);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Minha História', 57);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('MK III The Final Concerts [Disc 1]', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Physical Graffiti [Disc 1]', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Sambas De Enredo 2001', 21);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Supernatural', 59);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best of Ed Motta', 37);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Essential Miles Davis [Disc 1]', 68);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Essential Miles Davis [Disc 2]', 68);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Final Concerts (Disc 2)', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Up An'' Atom', 69);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vinícius De Moraes - Sem Limite', 70);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vozes do MPB', 21);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chronicle, Vol. 1', 76);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chronicle, Vol. 2', 76);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cássia Eller - Coleção Sem Limite [Disc 2]', 77);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cássia Eller - Sem Limite [Disc 1]', 77);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Come Taste The Band', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Deep Purple In Rock', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Fireball', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Machine Head', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Purpendicular', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Slaves And Masters', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Stormbringer', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Battle Rages On', 58);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vault: Def Leppard''s Greatest Hits', 78);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Outbreak', 79);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Djavan Ao Vivo - Vol. 02', 80);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Djavan Ao Vivo - Vol. 1', 80);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Elis Regina-Minha História', 41);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Cream Of Clapton', 81);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Unplugged', 81);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Album Of The Year', 82);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Angel Dust', 82);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('King For A Day Fool For A Lifetime', 82);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Real Thing', 82);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Deixa Entrar', 83);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('In Your Honor [Disc 1]', 84);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('In Your Honor [Disc 2]', 84);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('One By One', 84);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Colour And The Shape', 84);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('My Way: The Best Of Frank Sinatra [Disc 1]', 85);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Roda De Funk', 86);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('As Canções de Eu Tu Eles', 27);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Quanta Gente Veio Ver (Live)', 27);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Quanta Gente Veio ver--Bônus De Carnaval', 27);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Faceless', 87);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('American Idiot', 54);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Appetite for Destruction', 88);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Use Your Illusion I', 88);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Use Your Illusion II', 88);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Blue Moods', 89);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A Matter of Life and Death', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A Real Dead One', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A Real Live One', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Brave New World', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Dance Of Death', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Fear Of The Dark', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Iron Maiden', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Killers', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live After Death', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live At Donington 1992 (Disc 1)', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live At Donington 1992 (Disc 2)', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('No Prayer For The Dying', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Piece Of Mind', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Powerslave', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Rock In Rio [CD1]', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Rock In Rio [CD2]', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Seventh Son of a Seventh Son', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Somewhere in Time', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Number of The Beast', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The X Factor', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Virtual XI', 90);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Sex Machine', 91);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Emergency On Planet Earth', 92);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Synkronized', 92);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Return Of The Space Cowboy', 92);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Get Born', 93);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Are You Experienced?', 94);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Surfing with the Alien (Remastered)', 95);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Jorge Ben Jor 25 Anos', 46);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Jota Quest-1995', 96);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cafezinho', 97);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Living After Midnight', 98);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Unplugged [Live]', 52);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('BBC Sessions [Disc 2] [Live]', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Coda', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Houses Of The Holy', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('In Through The Out Door', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('IV', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Led Zeppelin I', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Led Zeppelin II', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Led Zeppelin III', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Physical Graffiti [Disc 2]', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Presence', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Song Remains The Same (Disc 1)', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Song Remains The Same (Disc 2)', 22);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A TempestadeTempestade Ou O Livro Dos Dias', 99);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mais Do Mesmo', 99);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Greatest Hits', 100);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Misplaced Childhood', 102);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Barulhinho Bom', 103);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Seek And Shall Find: More Of The Best (1963-1981)', 104);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of Men At Work', 105);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Black Album', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Garage Inc. (Disc 2)', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Kill ''Em All', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Load', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Master Of Puppets', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('ReLoad', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Ride The Lightning', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('St. Anger', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('...And Justice For All', 50);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Miles Ahead', 68);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Milton Nascimento Ao Vivo', 42);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Minas', 42);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Ace Of Spades', 106);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Demorou...', 108);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Motley Crue Greatest Hits', 109);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('From The Muddy Banks Of The Wishkah [Live]', 110);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Nevermind', 110);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Compositores', 111);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Olodum', 112);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Acústico MTV', 113);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Arquivo II', 113);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Arquivo Os Paralamas Do Sucesso', 113);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bark at the Moon (Remastered)', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Blizzard of Ozz', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Diary of a Madman (Remastered)', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('No More Tears (Remastered)', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Tribute', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Walking Into Clarksdale', 115);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Original Soundtracks 1', 116);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Beast Live', 117);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live On Two Legs [Live]', 118);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Pearl Jam', 118);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Riot Act', 118);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Ten', 118);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vs.', 118);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Dark Side Of The Moon', 120);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Os Cães Ladram Mas A Caravana Não Pára', 121);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Greatest Hits I', 51);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('News Of The World', 51);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Out Of Time', 122);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Green', 124);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('New Adventures In Hi-Fi', 124);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of R.E.M.: The IRS Years', 124);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cesta Básica', 125);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Raul Seixas', 126);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Blood Sugar Sex Magik', 127);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('By The Way', 127);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Californication', 127);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Retrospective I (1974-1980)', 128);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Santana - As Years Go By', 59);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Santana Live', 59);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Maquinarama', 130);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('O Samba Poconé', 130);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Judas 0: B-Sides and Rarities', 131);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Rotten Apples: Greatest Hits', 131);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A-Sides', 132);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Morning Dance', 53);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('In Step', 133);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Core', 134);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mezmerize', 135);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('[1997] Black Light Syndrome', 136);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live [Disc 1]', 137);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Live [Disc 2]', 137);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Singles', 138);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Beyond Good And Evil', 139);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Doors', 140);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Police Greatest Hits', 141);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Hot Rocks, 1964-1971 (Disc 1)', 142);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('No Security', 142);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Voodoo Lounge', 142);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Tangents', 143);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Transmission', 143);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('My Generation - The Very Best Of The Who', 144);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Serie Sem Limite (Disc 1)', 145);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Serie Sem Limite (Disc 2)', 145);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Acústico', 146);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Volume Dois', 146);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Battlestar Galactica: The Story So Far', 147);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Battlestar Galactica, Season 3', 147);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Heroes, Season 1', 148);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Lost, Season 3', 149);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Lost, Season 1', 149);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Lost, Season 2', 149);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Achtung Baby', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('All That You Can''t Leave Behind', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('B-Sides 1980-1990', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('How To Dismantle An Atomic Bomb', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Pop', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Rattle And Hum', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of 1980-1990', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('War', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Zooropa', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('UB40 The Best Of - Volume Two [UK]', 151);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Diver Down', 152);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best Of Van Halen, Vol. I', 152);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Van Halen', 152);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Van Halen III', 152);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Contraband', 153);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vinicius De Moraes', 72);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Ao Vivo [IMPORT]', 155);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Office, Season 1', 156);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Office, Season 2', 156);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Office, Season 3', 156);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Un-Led-Ed', 157);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Battlestar Galactica (Classic), Season 1', 158);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Aquaman', 159);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Instant Karma: The Amnesty International Campaign to Save Darfur', 150);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Speak of the Devil', 114);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('20th Century Masters - The Millennium Collection: The Best of Scorpions', 179);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('House of Pain', 180);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Cake: B-Sides and Rarities', 196);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('LOST, Season 4', 149);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Quiet Songs', 197);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Muso Ko', 198);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Realize', 199);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Every Kind of Light', 200);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Duos II', 201);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Worlds', 202);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Best of Beethoven', 203);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Temple of the Dog', 204);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Carry On', 205);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Revelations', 8);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Adorate Deum: Gregorian Chant from the Proper of the Mass', 206);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Allegri: Miserere', 207);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Pachelbel: Canon & Gigue', 208);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Vivaldi: The Four Seasons', 209);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: Violin Concertos', 210);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: Goldberg Variations', 211);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: The Cello Suites', 212);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Handel: The Messiah (Highlights)', 213);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The World of Classical Favourites', 214);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Sir Neville Marriner: A Celebration', 215);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mozart: Wind Concertos', 216);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Haydn: Symphonies 99 - 104', 217);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Beethoven: Symhonies Nos. 5 & 6', 218);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A Soprano Inspired', 219);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Great Opera Choruses', 220);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Wagner: Favourite Overtures', 221);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Fauré: Requiem, Ravel: Pavane & Others', 222);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Tchaikovsky: The Nutcracker', 223);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Last Night of the Proms', 224);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Puccini: Madama Butterfly - Highlights', 225);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Pavarotti''s Opera Made Easy', 227);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 228);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Carmina Burana', 229);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('A Copland Celebration, Vol. I', 230);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: Toccata & Fugue in D Minor', 231);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Prokofiev: Symphony No.1', 232);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Scheherazade', 233);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: The Brandenburg Concertos', 234);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Chopin: Piano Concertos Nos. 1 & 2', 235);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mascagni: Cavalleria Rusticana', 236);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Sibelius: Finlandia', 237);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Beethoven Piano Sonatas: Moonlight & Pastorale', 238);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Great Recordings of the Century - Mahler: Das Lied von der Erde', 240);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Adams, John: The Chairman Dances', 242);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory', 243);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Prokofiev: Romeo & Juliet', 245);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Strauss: Waltzes', 226);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Berlioz: Symphonie Fantastique', 245);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bizet: Carmen Highlights', 246);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('English Renaissance', 247);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Handel: Music for the Royal Fireworks (Original Version 1749)', 208);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mozart Gala: Famous Arias', 249);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('SCRIABIN: Vers la flamme', 250);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Armada: Music from the Courts of England and Spain', 251);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mozart: Symphonies Nos. 40 & 41', 248);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Back to Black', 252);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Frank', 252);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Carried to Dust (Bonus Track Version)', 253);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Beethoven: Symphony No. 6 ''Pastoral'' Etc.', 254);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bartok: Violin & Viola Concertos', 255);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mendelssohn: A Midsummer Night''s Dream', 256);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Bach: Orchestral Suites Nos. 1 - 4', 257);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Charpentier: Divertissements, Airs & Concerts', 258);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('South American Getaway', 259);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Górecki: Symphony No. 3', 260);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Purcell: The Fairy Queen', 261);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('The Ultimate Relexation Album', 262);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Purcell: Music for the Queen Mary', 263);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Weill: The Seven Deadly Sins', 264);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Szymanowski: Piano Works, Vol. 1', 266);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Nielsen: The Six Symphonies', 267);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Great Recordings of the Century: Paganini''s 24 Caprices', 268);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Liszt - 12 Études D''Execution Transcendante', 269);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Respighi:Pines of Rome', 226);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Schubert: The Late String Quartets & String Quintet (3 CD''s)', 272);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Monteverdi: L''Orfeo', 273);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Mozart: Chamber Music', 274);
INSERT INTO `Album` (`Title`, `ArtistId`) VALUES ('Koyaanisqatsi (Soundtrack from the Motion Picture)', 275);
